### ISSUE TITLE
SQLTransientConnectionException / NPE Connection issue

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1029]
**Versions**
5.24.1 build 448

**Describe the bug**
Saw this error.
https://pastebin.com/raw/SGUUyRYi
Strange that Votingplugin seems to have lost the connection.
Other plugins didn't notice outage. Votingplugin connects directly to an IP. Players didn't notice anything strange.
Edit: votingplugin on other servers worked just fine without any issues.

**To Reproduce**
Just this incident

**Expected behavior**
I doubt there was a connection loss, but if so, a more compact error would be nice.

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**
Hosting confirms that there were no issues on the systems monitoring.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

You can try that build. I made some changes to how mysql is handled, it may or may not help.

Just note any other plugins using the api (placeholderapi expansion, leaderboards) will break due to some of the changes

You can also try to increase max connections (may or may not help)

On another note, does it just work fine after a while? Or does it need a restart or /av reload?

Incase you need an updated expansion:
https://www.dropbox.com/s/uz15rf1rdacdn3m/Expansion-VotingPlugin.jar?dl=0

**Comment by x1p** [comment]
It happened twice. All within 2 minutes. No errors after that.

I'll guess I'll try first to raise the number of connections.

**Comment by BenCodez** [comment]
Hmm. Alright, something happened then.

**Comment by x1p** [comment]
Searched more logs. Found more errors on different timestamps. Just a few minutes apart from this error.
I guess something must have happened although hosting can't confirm.

- Hub server: 15:44
- Game1: 15:44, 21:22, 21:23
- Game2: none
- Game3: none

**Comment by BenCodez** [comment]
As long as it doesn't happen all the time I wouldn't worry too much about it.

**Comment by x1p** [comment]
Ok 👍
