### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by jsuarezl** [BenCodez/VotingPlugin#215]
Hi, I was trying to setup the plugin with MySQL storage for my server and when the plugin is loaded it throws an error with the MySQL database, here is the log of the plugin startup
https://hastebin.com/ekajivapax.md
Checking the database I noticed that the plugin never created any table, after enabling debug this is the startup log
https://hastebin.com/damuzojabu.md

**Comment by BenCodez** [comment]
Try to create the table manually. Had a few people tell me of a problem like this and can't never seem to fix it.

https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/mysql/MySQL.java#L55

Code to the actual querry ^

If you get the error try using VARCHAR(191) instead of VARCHAR(255), or TEXT (Try this one first, might be the simple solution) even. Let me know how that works, maybe I can fix

**Comment by BenCodez** [comment]
Try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by jsuarezl** [comment]
Used the dropbox plugin and worked fine, the tables are created and the data is correctly saved

**Comment by BenCodez** [comment]
Good to hear. Guess I finally solved that problem. Gonna leave this open until I release a version on spigot fixing it (probably saturday/sunday)

**Comment by BenCodez** [comment]
Version up on Spigot.
