### ISSUE TITLE
[Suggestion] Command for remove players in database by uuid

### ISSUE THREAD

**Issue by SeruhioX** [BenCodez/VotingPlugin#342]
I would like to propose a command to remove users by uuid from the database.

Perhaps a better solution would be that two users can not share their nick, since sometimes there are two users with the same name but different uuid and it does not work correctly, when it happens I have to eliminate the duplicate of the database.

Something like check the name and if it has the same but different uuid is updated, so always give it to the correct username.

**Comment by BenCodez** [comment]
Two users can't have the same name, that shouldn't be a problem.

**Comment by SeruhioX** [comment]
If you use a plugin like "FastLogin" or "Auto-In", if there can be two users with the same name, your uuid in online and offline mode.

Although this happens rarely (since my database has more than 12 thousand users) and has only happened 4-5 times.

**Comment by BenCodez** [comment]
Probably not the best idea to have online and offline uuids on the same server.... not much I can do with that.

I'll add the command though.

**Comment by SeruhioX** [comment]
Thank you for implementing it and I have a problem to report.

Today we have changed of month and I have enabled that of the rewards to only 10 users, the thing is that it is giving it to a lot more people and I do not know why.

https://i.gyazo.com/10445c44122926ee9a26ad31c6280486.png

https://i.gyazo.com/7b70d97457f9def2339a91bef879f60b.png

In the images you can see how it gives the same position to several people

No errors in log :S

**Comment by BenCodez** [comment]
It also count ties. Probably should add an option for that

On Feb 1, 2018 11:43 AM, "SeDark" <notifications@github.com> wrote:

Thank you for implementing it and I have a problem to report.

Today we have changed of month and I have enabled that of the prizes to
only 10 users, the thing is that it is giving it to a lot more people and I
do not know why.

https://i.gyazo.com/10445c44122926ee9a26ad31c6280486.png

https://i.gyazo.com/7b70d97457f9def2339a91bef879f60b.png

In the images you can see how it gives the same position to several people

No errors in log :S

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/342#issuecomment-362325747>,
or mute the thread

**Comment by SeruhioX** [comment]
I have not understood sorry, why have the rewards been quadrupled or more?

**Comment by BenCodez** [comment]
If two people are tied for first place they both get the first place reward. Then the third person will get the second top voter reward.

**Comment by SeruhioX** [comment]
I understand, I trust that you solve it, since it is quite confusing, when you think in a top, you do not think that several people can have the same position.

Thx in advance

**Comment by BenCodez** [comment]
Already implemented an option for it to for the next update
