### ISSUE TITLE
Issue/Question

### ISSUE THREAD

**Issue by Slimerblue22** [BenCodez/VotingPlugin#354]
I'm having problems getting votes to register in the server, the vote sites seem to work fine, they register the votes on the original voting site but nothing ends up happening on the server. It doesn't seem to even know anyone voted.

My voting sites config: https://pastebin.com/v0TMvkWn

1.12.1 server

**Comment by BenCodez** [comment]
1. Check your votifier configs, port taken?
2. I haven't yet seen a service site with "http:/", remove that

**Comment by Slimerblue22** [comment]
Remove the "http:/" from only service site or vote url as well?

**Comment by BenCodez** [comment]
Just the service site

**Comment by luc819** [comment]
same problem here
and i have not put the https

**Comment by luc819** [comment]
https://pastebin.com/se5K2hxJ

**Comment by BenCodez** [comment]
Are you getting the vote?

**Comment by luc819** [comment]
what do you mean ?

**Comment by luc819** [comment]
i am not getting anithing no reward no msg like you votes nothing i have try 2 different site i am searching for at leats 4 hour

**Comment by luc819** [comment]
i wont quit :)

**Comment by BenCodez** [comment]
Check your votifier connection from the voting site. Try changing ports.

**Comment by luc819** [comment]
i have test with the site everything is ok i am using port 6969

**Comment by luc819** [comment]
i did test with https://mctools.org/votifier-tester its says : Vote by %player% succesfully sent to ***.***.***.***

**Comment by luc819** [comment]
but it take around 5 min to have it succedfully

**Comment by luc819** [comment]
i have try 0.0.0.0 and its says succesfully instant 
but nothnig appen in the server

**Comment by BenCodez** [comment]
Anything in console when you vote?

**Comment by luc819** [comment]
i think its the problem nuvotifier dosent sent nothing to the server ill check with them boss :)

**Comment by BenCodez** [comment]
Probably just are using a port that's already taken

**Comment by luc819** [comment]
i have try 10 different :(

**Comment by luc819** [comment]
do i need to restart each time i change the port ?

**Comment by luc819** [comment]
i have try with 0.0.0.0 and still nothing appen

**Comment by BenCodez** [comment]
1. Are you updating the voting site?
2. Restart each time
3. Any errors on startup?
4. Turn debug on in votifier.

**Comment by luc819** [comment]
its probaly something very basic  because it should send info to the console when i do the test but i have nothing i have try on mclist site and its working on theyr test program but still nothing on console i have try switching between nuvotifier and votifier and still nothing append i have try defautl port and so many other  i have try debug mode but it fail on nuvotifier test or votifier no eror on startup 
02:01:10] [Server thread/INFO]: [Votifier] Enabling Votifier v1.9
[02:01:10] [Server thread/INFO]: [Votifier] Votifier enabled.
[02:01:10] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.12.6
[02:01:11] [Server thread/INFO]: [VotingPlugin] Enabled VotingPlugin 5.12.6
[02:01:11] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from liste-serv-minecraft.fr, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

**Comment by BenCodez** [comment]
It's an issue on votifier's end.

**Comment by luc819** [comment]
thats what i thouth too

**Comment by luc819** [comment]
i have 1.11.2 should i keep trying with votifier or go directly to nuvotifier ?

**Comment by BenCodez** [comment]
Votifier works just fine. Up to you.

**Comment by luc819** [comment]
ill follow ur advise ill find something  do you thing its my host that is locking port ?

**Comment by BenCodez** [comment]
Could be. Ask them for a port.

**Comment by luc819** [comment]
they says thats port that is open its between 30000 34000 but in votifier they say only use 4 number port

**Comment by BenCodez** [comment]
Well, get a better host

**Comment by MelonCola** [comment]
Regarding Slimerblue's issue, I'm a dev on the server he's talking about, the plugin's working fine, we're having other issues which we are aware how to resolve, but they make this seem like it doesn't work. It does, as I tested it with my test website, so if you wanna like close the issue or whatever. :P

**Comment by Slimerblue22** [comment]
^^ I'll confirm that

**Comment by luc819** [comment]
now votifier is working i have tested from a mc list site and i receive the reward but when a player vote from the server they do not receive nothing

**Comment by BenCodez** [comment]
@luc819 that doesn't make much sense

On Feb 20, 2018 10:06 PM, "luc819" <notifications@github.com> wrote:

now votifier is working i have tested from a mc list site and i receive the
reward but when a player vote from the server they do not receive nothing

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/354#issuecomment-367199308>,
or mute the thread
