### ISSUE TITLE
WARN [VotingPlugin] No vote has been recieved from https://mc-servers.com, may be an invalid service site

### ISSUE THREAD

**Issue by byluz** [BenCodez/VotingPlugin#583]
Hi, so a user said that the plugin thinks my server list is not valid? I have tested voting on other servers and everything works as expected so votifier is working on my end? His config seems to be fine. The warn is below:

`WARN [VotingPlugin] No vote has been received from https://mc-servers.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier`

https://pastebin.com/ApzSbi2p

His vote sites config is attached!

**Comment by BenCodez** [comment]
1. Just use pastebin
2. Means the server hasn't received the vote from that service site specified.
Just check console when you vote, if you get nothing then it's a votifier problem, if you get something, it will say the service site, and even auto gen the site.

**Comment by byluz** [comment]
I am the owner of the server list and I have not had any issues. My votifier works as other servers are using it just fine right now!

https://pastebin.com/ApzSbi2p

**Comment by BenCodez** [comment]
I didn't say it was on your end. I've dealt with this problem a million times. Majority of the time is the user setting up votifier not knowing how to use it as it was intended. (or able to read console logs...) Or just the user putting the wrong service site.

That's why the plugin is saying that message, to help users figure it, as I get a message about this same issue a few times a week or more sometimes. It's never the voting site's fault (maybe a rare case, which I have yet to find)

**Comment by byluz** [comment]
Ahh okay, that must be it then. I just found it weird that other sites he setup were working?

**Comment by BenCodez** [comment]
Just the user to check console when they vote, it will say if there is a problem.

**Comment by byluz** [comment]
Yeah he says nothing shows up in the console?

**Comment by BenCodez** [comment]
Then votifier isn't getting the vote.
